### ISSUE TITLE
TCP for core to services communication

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/core#119]
As #117, services have to use a socket to communicate with the core.
Why not use TCP as Docker easily allow links between containers?

**Comment by antho1404** [comment]
now services have their own networks and so don't have access to the daemon container (for the network part) that's why I shared the socket like that they don't need to share a network.

Now that the daemon runs in its own container we could grant it access to all the networks of all the service.

What I like with the socket it's that only the socket is shared so the service is really in its own environment. If we share the same network we can start to have some problems, for example the service who define a port that is already used by the core

**Comment by antho1404** [comment]
first for the socket in windows it's not a problem, the socket is not used by anything in the host machine, only by the docker containers (https://github.com/mesg-foundation/core/pull/117#issuecomment-386559893) so this is not an issue for windows or any other OS

For the networks part, yes it's possible to have the container(s) of the service and the core container in the same network, but it means the core container will have n+1 networks for n services that it runs + the network to expose the api, with the socket the core container will only have one network that publish the port to access the daemon api.

So for me it looks way more complicated with networks for no benefits and we don't have to worry about socket compatibility, it's inside docker so everything will be fine.

If you have good reasons to implement TCP over socket I'm all open but if not and if it's just preferences I think its not worth the complexity

**Comment by antho1404** [comment]
@NicolasMahe what do you think about closing this one ?

**Comment by NicolasMahe** [comment]
Yes let's close for now.. My searches also says that TCP sharing is more complex with a lot of network.
