### ISSUE TITLE
Use a tag system to identify requests

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/core#201]
It will be nice to be able to listen to a specific `executionID` in the API `Core.ListenResult`.
The core could also close the stream when the result with the right `executionID` is send back.

**Comment by antho1404** [comment]
This system to listen a result of a task based on the `executionID` is not really valid.
If the task is fast we will have some concurrency issues where the task will be finished before the stream is even created so this is not a solution.

A solution could be that the application generate its own `executionID` but this is not valid too because we might have some collusions on the `executionID`

On good solution is to use a tag system.

When the application wants to listen a specific task, it can create a unique id for this task, listen the result for this specific unique id and only then execute the task with this unique id.

Also to be more generic we could add any kind of tags, in order to have some metadata associated to this task like tags in time series database that let you then filter on your different tags.

We should for every execution associate a map of tags with `name => value` and we should allow the `ListenResult` to filter on tags.

**Comment by NicolasMahe** [comment]
Could name it **label** instead of tag

**Comment by antho1404** [comment]
after reflection, I prefer `tag` instead of `label`
For me I feel like labels is good for metadata, some additional informations to **describe** and tag is more about **processing** kind of.
I see labels as a special tag for semantic only and in our case we want to use it for processing but after it's just my feeling about it and I would be happy to debate about it
