### ISSUE TITLE
deamon.Status() should check container status

### ISSUE THREAD

**Issue by pts-solutions** [mesg-foundation/core#293]
the problem found here is that in the current implementation when the cli checks if mesg-core is running, it just goes and checks if the service is around, which leads to that both mesg-core start and mesg-core status report that everything is fine, but as illustrated in the screenshot below that is far away from the truth.

![image](https://user-images.githubusercontent.com/3125440/42992959-58393e4e-8c34-11e8-947b-5ddcba7341ac.png)

in fact in this example mesg-core even panic'd and still the client is reporting that all is fine. i won't go into details about why it panic'd, that will be part of a PR i am going to make soon, to also allow service and app development under windows.

**Comment by NicolasMahe** [comment]
Yes indeed. The line involve is:
https://github.com/mesg-foundation/core/blob/1ea198b5ad5e341fea7692024c37d7f41c76ee18/daemon/status.go#L9

Right now, we have 2 functions: `ServiceStatus` and `Status` (this one returns only the container's status but because the package name is `container` it's better to not named it `ContainerStatus`).

The best solution, is to create one common function that check both the service and the container.

Related functions:
https://github.com/mesg-foundation/core/blob/1ea198b5ad5e341fea7692024c37d7f41c76ee18/container/container.go#L36-L50

https://github.com/mesg-foundation/core/blob/1ea198b5ad5e341fea7692024c37d7f41c76ee18/container/service.go#L73-L82

**Comment by antho1404** [comment]
fixed with https://github.com/mesg-foundation/core/pull/411
