### ISSUE TITLE
cmd: improvments

### ISSUE THREAD

**Issue by krhubert** [mesg-foundation/core#355]
- [ ] keep consistency between `Short` and `Long` description (print required arguments, etc...)
- [x] print errors to `stderr`
- [x] do not print color output
- [x] remove `publish` alias from `service deploy` cmd
- [x] `service delete` cmd should continue deletion after errors (eg, not found error)
- [x] `service delete` - add --force|-f flag for skipping prompt
- [x] `service init` clean up on `CTRL+C`
- [ ] `service init` do not write to existing directory (+remove current option)
- [x] `service  stop` panics without arguments
- [ ] `servcie` cmd - add `--verbose` flag for more technical/detalied errors
- [ ] `servcie` - consistent output when mesg-core is not run
- [x] `service list` - print in column
- [x] remove spinner

**Comment by antho1404** [comment]
It looks like you started the work on this one but I think we should discuss on some of these things, I personally disagree with some of them or at least we need to discuss about.

- **do not print color output**: In the core I agree, in the CLI we still might need it in some places. Colors are nice for users and not everyone is a sysadmin that needs to script the outputs of the CLI. I don't think we should drop the support of the colors.

- ** service delete**: I personally prefer a `--confirm` instead of `--force` that sound like even if there is an issue while deleting we force the deletion

- **remove spinner**: Same as the colors, I agree for sysadmin it can be annoying but for user experience it's really good so I would prefer to keep it except if there is some real arguments against it.

Also I think this issue should split into multiple issues. Some are about improvements, some bugs, some quite critical, some not at all.

**Comment by krhubert** [comment]
> Colors are nice for users and not everyone is a sysadmin that needs to script the outputs of the CLI

But you have to have options for a sysadmin (it could be flag --color/--no-color). I know not everyone is a sysadmin, but adding color won't make that some inexperienced developer will start to understand how mesg works. You have to take care of both (but sysadmin first). You have to give them tools for running mesg (scalling it, gather logs etc) because experienced users will be the one who run dozen of mesg nodes (in some orchestrator like swarm/kubernetes,bare metal...). Look at cyrptominers - now every server farm is automated and nobody runs single node (maybe to play with it). We have to aim for simplifying mesg for sysadmin first.

> I personally prefer a --confirm instead of --force

--force is a standard way to avoid confirmation (sometimes --quiet flag is used), but I've --confirm is very rare and unintuitive. So I would stay with --force/--quiet.

> Same as the colors, I agree for sysadmin it can be annoying but for user experience it's really good so I would prefer to keep it except if there is some real arguments against it.

Same as above. Spinners only complete things. It makes harder to write scripts and what value them adding besides spinning circle? It makes writing cli more complicated because you have to think of future usage. (Let's suppose someone wants to capture output from starting most-core to display msg in the web (or in ansible/puppet/chef) and then what? He will get a spinner....)

> Also I think this issue should split into multiple issues. 

I wanted to, but when I started splitting then there were a lot of issues and I decided to put more time/focus on the solution, less how to split issues.

**Comment by NicolasMahe** [comment]
What about adding a general flag for sysadmin that remove spinner and color? But keep it by default the user friendliness.

**Comment by krhubert** [comment]
follow https://github.com/mesg-foundation/core/issues/375
