### ISSUE TITLE
Cannot connect to other dependencies inside a service

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/core#533]
When creating other dependencies for a service, the goal is to be able to connect these other dependencies but right now there is no way to do that.

Let's take the following service:
```yml
name: "influxDB"
dependencies:
  influxdb:
    image: influxdb
    ports:
      - "8086"
    volumes:
      - /var/lib/influxdb
```

In my application I should be able to connect to endpoint of this dependency with something like `influxdb:8086` but instead, to connect to this dependency we need to access using the container name which is based on the service hash and so there is no way to predict it directly.

In this example I need to connect to this endpoint `core-e00a68dcd22cd77d996ce540e9113feaa75f92e8-influxdb.1.xd6ps2z5xt2ye81c36hwvb13k:8086` or `core-e00a68dcd22cd77d996ce540e9113feaa75f92e8-influxdb:8086`

I don't really mind having to use this long name if it's at least given in an env variable like 

```
INFLUXDB_HOST_1=core-e00a68dcd22cd77d996ce540e9113feaa75f92e8-influxdb.1.xd6ps2z5xt2ye81c36hwvb13k # the one created for the specific docker task
INFLUXDB_HOST=core-e00a68dcd22cd77d996ce540e9113feaa75f92e8-influxdb # the one associated to the service
```

Or even better be able to access the host `influxdb` directly but this can be complicated and can create some problems if names already exists.

**Comment by ilgooz** [comment]
Resolving env vars to server addresses can be problematic in various programs. I think we should solve this problem in the DNS level and keep the _influxdb:8086_ as it's.

This might be achieved by configuring the _/etc/hosts/_ file while starting the services but this can be problemetic because in this case we'll need to modify the _Dockerfiles_ that created by the devs.

A more stable solution requires this kinda configurations to be made while starting the services with some flags. 

Useful links:
* https://docs.docker.com/v17.09/engine/userguide/networking/default_network/configure-dns/
* https://docs.docker.com/v17.09/engine/userguide/networking/configure-dns/
* https://docs.docker.com/docker-cloud/apps/service-links/
* https://docs.docker.com/config/containers/container-networking/#dns-services

**Comment by ilgooz** [comment]
@NicolasMahe _--hostname_ option can be the solution while [creating](https://docs.docker.com/engine/reference/commandline/service_create/) services, investigating it

**Comment by NicolasMahe** [comment]
We need the option from the API of docker. See: https://docs.docker.com/engine/api/v1.37/

**Comment by NicolasMahe** [comment]
What about the API version?

**Comment by ilgooz** [comment]
I didn't see the api version specified in the docs but we have the feature in the docker client [package](https://godoc.org/github.com/docker/docker/api/types/swarm#NetworkAttachmentConfig).
