### ISSUE TITLE
Move logic of stopping core and services to api or daemon package

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/core#576]
Now, when stopping the core (command `mesg-core stop`), the CLI manually load and stop services before stopping the core.
This logic should be move in `API` or `daemon` package.

Concerned source code:
https://github.com/mesg-foundation/core/blob/a5a1dc6fb4640a2a43366be0fcf59191c36794fb/commands/provider/core_provider.go#L34-L72

**Comment by krhubert** [comment]
That would be good start, but for now we are listing services from the database.

Maybe we should add label to each container and just create a function `container.StopService(filter/label)`

And in daemon - container.StopService("mesg-label")

Because overall we don't need to list service from a database, but rather from current stat of docker containers.

**Comment by NicolasMahe** [comment]
Moved to https://forum.mesg.com/t/move-logic-of-stopping-core-and-services-to-api-or-daemon-package/146
