### ISSUE TITLE
Command execute doesn't allow repeated types

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/core#681]
This PR https://github.com/mesg-foundation/core/pull/679 introduced a new data type: `repeated data`

This file https://github.com/mesg-foundation/core/blob/master/utils/servicecasting/cast.go doesn't do anything about repeated parameters and so the command `service execute` cannot handle repeated data with the flag `--data`

**Comment by antho1404** [comment]
Future types like `Any` and `Object` need to be tested as well

**Comment by krhubert** [comment]
How do we want to represent the repeated types in cli?

**Comment by antho1404** [comment]
Some ideas:
- `--data foo=[a, b, c]`
- `--data foo.0=a --data foo.1=b --data foo.2=c`
- `--data foo=a,b,c`
- Maybe we just support repeated with the `--json` and not the `--data`

**Comment by NicolasMahe** [comment]
Let's see what is the simplest to implement in `xpflag.NewStringToStringValue`.

I like `--data foo=[a, b, c]`.

**Comment by ilgooz** [comment]
I think repeated types can be supported with both `-d a=1,2` & `-d a=1 -d a=2` syntaxes.
And objects should be only supported with _json_ option as suggested. Because it can be really hard to deal with nested data specially if the data has too many fields. So, in the real world, devs aren't going to use it because of the complexity anyway.

**Comment by NicolasMahe** [comment]
let's go with the simplest implementation!
