### ISSUE TITLE
Core and service protobuf needs cleaning

### ISSUE THREAD

**Issue by krhubert** [mesg-foundation/core#834]
Issues that we have right now:

1) core return `ExecutionID` for executionTask, but there is no api to get result by this `ExecutionID`
2) emit event is done in service api, but execution task is done in core api
3) listen task is done in service api, but listen event is done in core api (so the opposite)
4) event has no id
5) more??

So api has few non-consistent things out there. It's a starting point for api changes but the sooner we start talking about the better.

**Comment by antho1404** [comment]
I don't see the inconsistency with
- `listenEvent` in core and `emitEvent` in service
- `listenTask` in service and `executeTask` in core

maybe on the naming but i'm not really sure what you mean by inconsistency here.

Agree for the execution api(s), also the event ID. For this part please read the section 3.1 in the [network of services document](https://mesg.com/documents/decentralized-network-of-services.pdf)

**Comment by NicolasMahe** [comment]
> * emit event is done in service api, but execution task is done in core api
> * listen task is done in service api, but listen event is done in core api (so the opposite)

The reason is to have 2 separate API Core and Service.
Core API should be only available "outside" the core, for creating application.
Service API should be only available "inside" services.
The problem is, currently, both are running on the same server and thus are available on both "side".
I'm not sure it's really something we want to keep, depending on the solution we choose for service composition.

> * core return `ExecutionID` for executionTask, but there is no api to get result by this `ExecutionID`
As we spoke a few months ago, a few API (`listenTask`, `listenResult`) could be merge into a common `listenExecution` API. New API to get previous `Execution` and to create an execution (currently named `executeTask`) will be really nice also.

> * event has no id
Yes currently event has no id. We plan to offer the possibility to Service to emit event with specific id, with a fallback to a generated one. It will be mandatory with the decentralized network when multiple core running the same service emit the same event to know that the events are the same.

**Comment by krhubert** [comment]
> Core API should be only available "outside" the core, for creating application.
Service API should be only available "inside" services.

Yes I know, but looking at ListenEvent/Task and ExecuteTask/EmitEvent split between proto files, now service needs to use both for managing events/tasks.

Just wanted to start this discussion because the sooner we change api the fewer changes it will require in other services.

**Comment by krhubert** [comment]
> I don't see the inconsistency with
- listenEvent in core and emitEvent in service
- listenTask in service and executeTask in core

The point is we have:
- ListenEvent and ExecuteTask task in core
- ListenTask and EmitEvent in service

It should look like the one you post.

Also one thing worth mentioning, in the cli we don't have option to emit an event (only execute the task).

**Comment by antho1404** [comment]
It is like the one I posted
- [listenEvent](https://github.com/mesg-foundation/core/blob/master/protobuf/coreapi/api.proto#L17) in core and [emitEvent](https://github.com/mesg-foundation/core/blob/master/protobuf/serviceapi/api.proto#L18) in service
- [listenTask](https://github.com/mesg-foundation/core/blob/master/protobuf/serviceapi/api.proto#L22) in service and [executeTask](https://github.com/mesg-foundation/core/blob/master/protobuf/coreapi/api.proto#L23) in core

Also what you say is the same
- ListenEvent and ExecuteTask task in core
- ListenTask and EmitEvent in service

| method | api |
| --- | --- |
| ListenEvent | Core |
| ExecuteTask | Core |
| ListenTask | Service |
| EmitEvent | Service |

Am i really not seeing something here ?
