### ISSUE TITLE
Service marketplace connection drop

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/core#917]
I didn't find a specific way to reproduce this yet, maybe when my computer goes from sleep to awake but it happened many time. 

Once this error happens, then I have it non-stop and the marketplace service becomes useless

```
service | catch polling Error: Invalid JSON RPC response: ""
service |     at Object.InvalidResponse (/app/node_modules/web3-core-helpers/src/errors.js:42:16)
service |     at XMLHttpRequest.request.onreadystatechange (/app/node_modules/web3-providers-http/src/index.js:92:32)
service |     at XMLHttpRequestEventTarget.dispatchEvent (/app/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
service |     at XMLHttpRequest._setReadyState (/app/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
service |     at XMLHttpRequest._onHttpRequestError (/app/node_modules/xhr2-cookies/dist/xml-http-request.js:349:14)
service |     at ClientRequest.<anonymous> (/app/node_modules/xhr2-cookies/dist/xml-http-request.js:252:61)
service |     at ClientRequest.emit (events.js:182:13)
service |     at TLSSocket.socketErrorListener (_http_client.js:391:9)
service |     at TLSSocket.emit (events.js:182:13)
service |     at emitErrorNT (internal/streams/destroy.js:82:8)
service |     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
service |     at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by antho1404** [comment]
even my calls are rejected, this is not only the polling.

```
service | error in preparePublishServiceVersion Error: Invalid JSON RPC response: ""
service |     at Object.InvalidResponse (/app/node_modules/web3-core-helpers/src/errors.js:42:16)
service |     at XMLHttpRequest.request.onreadystatechange (/app/node_modules/web3-providers-http/src/index.js:92:32)
service |     at XMLHttpRequestEventTarget.dispatchEvent (/app/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
service |     at XMLHttpRequest._setReadyState (/app/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
service |     at XMLHttpRequest._onHttpRequestError (/app/node_modules/xhr2-cookies/dist/xml-http-request.js:349:14)
service |     at ClientRequest.<anonymous> (/app/node_modules/xhr2-cookies/dist/xml-http-request.js:252:61)
service |     at ClientRequest.emit (events.js:182:13)
service |     at TLSSocket.socketErrorListener (_http_client.js:391:9)
service |     at TLSSocket.emit (events.js:182:13)
service |     at emitErrorNT (internal/streams/destroy.js:82:8)
service |     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
service |     at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by antho1404** [comment]
Might be related to https://github.com/INFURA/infura/issues/58

**Comment by NicolasMahe** [comment]
I let the core runs on my macbook since yesterday with multiple change of location (so no more wifi).
This morning, the logs of the marketplace was showing the `Error: Invalid JSON RPC response: ""`, I tried to execute the task `getService` but also get the `Error: Invalid JSON RPC response: ""`, tried a second times and it returns the correct result 👍 
The listener of new block also reconnect just after the second attempt to execute a task.

I think I was able to reproduce the problem in a shorter time:
- Run the core
- Show marketplace logs
- Wait to see `new block XXXX`
- Cut internet
- Wait a few minutes (maybe as long as 12.5min)
- Connect to internet
- The logs of marketplace should not display any new error
- Execute task getService `./dev-cli service execute marketplace --task getService --data sid=com.mesg.bitcoin`. Either the command wait forever or get `{"message":"Invalid JSON RPC response: \"\""}`.
- Wait few more minutes until the logs of marketplace show either a lots of new error and/or `new block XXX`
- Execute task getService again. It should work
